### ISSUE TITLE
Re-rendering is not happening on the fly while changing any Element property

### ISSUE THREAD

**Issue by amreesht** [Kliton/yt_pageform#4]
Hi, Thanks for such an awesome project. 

I just observed that making change to any element property from input box or Required button, is not reflected immediately. You need to click outside that property then it is reflected in Designer Element.

May be I am not as good as you are in react, but I was just trying to fix this, but don't know how to fix. I tried to use register and watch but nothing worked. 

Any idea how to fix it.

**Comment by Kliton** [comment]
Hi, this happens because useForm hook is set with mode `onBlur`.

You can change it to: `onChange` to trigger changes on every keystroke.

```ts const form = useForm<propertiesFormSchemaType>({
    resolver: zodResolver(propertiesSchema),
    mode: "onBlur", //<=========== HERE
    defaultValues: {
      label: element.extraAttributes.label,
      helperText: element.extraAttributes.helperText,
      required: element.extraAttributes.required,
      placeHolder: element.extraAttributes.placeHolder,
    },
  });```

**Comment by amreesht** [comment]
Thanks for the respond.  I tried that but that was not working. :( 

Though I changed following:
```js
<Input
   {...field}
   onKeyDown={(e) => {
         if (e.key === "Enter") e.currentTarget.blur();
      }}
 />
```

to 
```js
<Input
    {...field}
      onKeyUp={(e) => {
          e.currentTarget.blur();
          e.currentTarget.focus();
      }}
  />
```
And it worked. I know it is not a good approach but don't see any other way to do it. Also not sure how to handle required checkbox.
